version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - '8080:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'